/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zgpdistribution.ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import zgpdistribution.util.CityDAO;
import zgpdistribution.util.CountryDAO;
import zgpdistribution.util.CustTypeDAO;
import zgpdistribution.util.CustomerDAO;
import zgpdistribution.util.StateDAO;
import zgpdistribution.util.TownshipDAO;
import zgpdistribution.util.oops.City;
import zgpdistribution.util.oops.Country;
import zgpdistribution.util.oops.CustType;
import zgpdistribution.util.oops.Customer;
import zgpdistribution.util.oops.State;
import zgpdistribution.util.oops.Township;

/**
 *
 * @author John
 */
public class CustomerRegDialogForm extends javax.swing.JDialog {

    private boolean status = false;

    /**
     * Creates new form CustomerRegDialogForm
     */
    public CustomerRegDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initFormData();
    }

    private void initFormData() {
        jComboBoxCustRegTownship.addItem("-- Select One --");
        jComboBoxCustRegTownship.setEnabled(false);
        jComboBoxCustRegCity.addItem("-- Select One --");
        jComboBoxCustRegState.addItem("-- Select One --");
        jComboBoxCustRegCountry.addItem("-- Select One --");
        jComboBoxCustRegCustType.addItem("-- Select One --");

        try {

            ArrayList<Township> tspList = new TownshipDAO().queryAll();
            for (Township township : tspList) {
                jComboBoxCustRegTownship.addItem(township.getName());
            }
            ArrayList<City> cityList = new CityDAO().queryAll();
            for (City city : cityList) {
                jComboBoxCustRegCity.addItem(city.getName());
            }
            ArrayList<State> stateList = new StateDAO().queryAll();
            for (State state : stateList) {
                jComboBoxCustRegState.addItem(state.getName());
            }
            ArrayList<Country> countryList = new CountryDAO().queryAll();
            for (Country country : countryList) {
                jComboBoxCustRegCountry.addItem(country.getName());
            }
            ArrayList<CustType> custTList = new CustTypeDAO().queryAll();
            for (CustType custType : custTList) {
                jComboBoxCustRegCustType.addItem(custType.getName());
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCustRegOutletName = new javax.swing.JLabel();
        jTextFieldCustRegOutletName = new javax.swing.JTextField();
        jLabelCustRegCustomerName = new javax.swing.JLabel();
        jTextFieldCustRegCustomerName = new javax.swing.JTextField();
        jLabelCustRegAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCustRegAddress = new javax.swing.JTextArea();
        jLabeCustReglTownship = new javax.swing.JLabel();
        jComboBoxCustRegTownship = new javax.swing.JComboBox();
        jLabelCustRegCity = new javax.swing.JLabel();
        jComboBoxCustRegCity = new javax.swing.JComboBox();
        jLabelCustRegState = new javax.swing.JLabel();
        jComboBoxCustRegState = new javax.swing.JComboBox();
        jLabelCustRegCountry = new javax.swing.JLabel();
        jComboBoxCustRegCountry = new javax.swing.JComboBox();
        jLabelCustRegPhone = new javax.swing.JLabel();
        jTextFieldCustRegPhone = new javax.swing.JTextField();
        jLabelCustRegMail = new javax.swing.JLabel();
        jTextFieldCustRegEmail = new javax.swing.JTextField();
        jLabelCustRegFax = new javax.swing.JLabel();
        jTextFieldCustRegFax = new javax.swing.JTextField();
        jLabelCustRegCustType = new javax.swing.JLabel();
        jComboBoxCustRegCustType = new javax.swing.JComboBox();
        jButtonCustRegCancel = new javax.swing.JButton();
        jButtonCustRegSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Customer Register");

        jLabelCustRegOutletName.setText("Outlet Name : ");

        jLabelCustRegCustomerName.setText("Customer Name : ");

        jLabelCustRegAddress.setText("Address : ");

        jTextAreaCustRegAddress.setColumns(20);
        jTextAreaCustRegAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCustRegAddress);

        jLabeCustReglTownship.setText("Township : ");

        jLabelCustRegCity.setText("City : ");

        jComboBoxCustRegCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCustRegCityItemStateChanged(evt);
            }
        });

        jLabelCustRegState.setText("State / Devision : ");

        jLabelCustRegCountry.setText("Country : ");

        jLabelCustRegPhone.setText("Phone : ");

        jLabelCustRegMail.setText("e-mail : ");

        jLabelCustRegFax.setText("Fax : ");

        jLabelCustRegCustType.setText("Customer Type : ");

        jButtonCustRegCancel.setText("Cancel");
        jButtonCustRegCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustRegCancelActionPerformed(evt);
            }
        });

        jButtonCustRegSave.setText("Save");
        jButtonCustRegSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustRegSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCustRegCustType)
                    .addComponent(jLabelCustRegCustomerName)
                    .addComponent(jLabelCustRegOutletName)
                    .addComponent(jLabelCustRegCity)
                    .addComponent(jLabelCustRegState)
                    .addComponent(jLabelCustRegCountry)
                    .addComponent(jLabelCustRegPhone)
                    .addComponent(jLabelCustRegMail)
                    .addComponent(jLabelCustRegFax)
                    .addComponent(jLabeCustReglTownship)
                    .addComponent(jLabelCustRegAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCustRegOutletName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustRegCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustRegTownship, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustRegCity, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustRegState, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustRegCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustRegFax, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustRegCustType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCustRegSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCustRegCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxCustRegCity, jComboBoxCustRegCountry, jComboBoxCustRegCustType, jComboBoxCustRegState, jComboBoxCustRegTownship, jScrollPane2, jTextFieldCustRegCustomerName, jTextFieldCustRegEmail, jTextFieldCustRegFax, jTextFieldCustRegOutletName, jTextFieldCustRegPhone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCustRegOutletName)
                            .addComponent(jTextFieldCustRegOutletName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCustRegCustomerName)
                            .addComponent(jTextFieldCustRegCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCustRegAddress)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCustRegTownship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeCustReglTownship))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCustRegCity)
                            .addComponent(jComboBoxCustRegCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCustRegState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCustRegState))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCustRegCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCustRegCountry))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCustRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCustRegPhone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCustRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCustRegMail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCustRegFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCustRegFax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCustRegCustType)
                            .addComponent(jComboBoxCustRegCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCustRegSave, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCustRegCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCustRegCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCustRegCityItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxCustRegCity.getSelectedItem().toString().equals("YANGON")) {
            jComboBoxCustRegTownship.setEnabled(true);
        } else {
            jComboBoxCustRegTownship.setSelectedIndex(0);
            jComboBoxCustRegTownship.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCustRegCityItemStateChanged

    private void jButtonCustRegCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustRegCancelActionPerformed
        // TODO add your handling code here:
        status = false;
        JOptionPane.showMessageDialog(this, "Distory Operation Successful");
        resetCustRegPannel();
        this.dispose();
    }//GEN-LAST:event_jButtonCustRegCancelActionPerformed

    private void jButtonCustRegSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustRegSaveActionPerformed
        // TODO add your handling code here:
        status = true;
        if (saveCustReg()) {
            JOptionPane.showMessageDialog(this, "Save Record Successful");
            resetCustRegPannel();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Save Record Fail");
        }
    }//GEN-LAST:event_jButtonCustRegSaveActionPerformed

    public boolean showForm() {
        this.setVisible(true);
        return status;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerRegDialogForm dialog = new CustomerRegDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void resetCustRegPannel() {
        jTextFieldCustRegOutletName.setText("");
        jTextFieldCustRegCustomerName.setText("");
        jTextAreaCustRegAddress.setText("");
        jComboBoxCustRegTownship.setSelectedIndex(0);
        jComboBoxCustRegCity.setSelectedIndex(0);
        jComboBoxCustRegState.setSelectedIndex(0);
        jComboBoxCustRegCountry.setSelectedIndex(0);
        jTextFieldCustRegPhone.setText("");
        jTextFieldCustRegEmail.setText("");
        jTextFieldCustRegFax.setText("");
        jComboBoxCustRegCustType.setSelectedIndex(0);
    }

    private boolean saveCustReg() {
        Customer cust = new Customer();
        cust.setOutletName(jTextFieldCustRegOutletName.getText().trim());
        cust.setCustomerName(jTextFieldCustRegCustomerName.getText().toUpperCase().trim());
        cust.setAddress(jTextAreaCustRegAddress.getText().trim());
        cust.setTownship(jComboBoxCustRegTownship.getSelectedItem().toString());
        cust.setCity(jComboBoxCustRegState.getSelectedItem().toString());
        cust.setState(jComboBoxCustRegState.getSelectedItem().toString());
        cust.setCountry(jComboBoxCustRegCountry.getSelectedItem().toString());
        cust.setPhone(jTextFieldCustRegPhone.getText().trim());
        cust.setEmail(jTextFieldCustRegEmail.getText().trim());
        cust.setFax(jTextFieldCustRegFax.getText().trim());
        cust.setCustomerType(jComboBoxCustRegCustType.getSelectedItem().toString());
        return new CustomerDAO().save(cust);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCustRegCancel;
    private javax.swing.JButton jButtonCustRegSave;
    private javax.swing.JComboBox jComboBoxCustRegCity;
    private javax.swing.JComboBox jComboBoxCustRegCountry;
    private javax.swing.JComboBox jComboBoxCustRegCustType;
    private javax.swing.JComboBox jComboBoxCustRegState;
    private javax.swing.JComboBox jComboBoxCustRegTownship;
    private javax.swing.JLabel jLabeCustReglTownship;
    private javax.swing.JLabel jLabelCustRegAddress;
    private javax.swing.JLabel jLabelCustRegCity;
    private javax.swing.JLabel jLabelCustRegCountry;
    private javax.swing.JLabel jLabelCustRegCustType;
    private javax.swing.JLabel jLabelCustRegCustomerName;
    private javax.swing.JLabel jLabelCustRegFax;
    private javax.swing.JLabel jLabelCustRegMail;
    private javax.swing.JLabel jLabelCustRegOutletName;
    private javax.swing.JLabel jLabelCustRegPhone;
    private javax.swing.JLabel jLabelCustRegState;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCustRegAddress;
    private javax.swing.JTextField jTextFieldCustRegCustomerName;
    private javax.swing.JTextField jTextFieldCustRegEmail;
    private javax.swing.JTextField jTextFieldCustRegFax;
    private javax.swing.JTextField jTextFieldCustRegOutletName;
    private javax.swing.JTextField jTextFieldCustRegPhone;
    // End of variables declaration//GEN-END:variables
}
